// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: game.proto
// Protobuf C++ Version: 5.29.5

#ifndef game_2eproto_2epb_2eh
#define game_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_game_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_game_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_game_2eproto;
namespace game {
class BulletState;
struct BulletStateDefaultTypeInternal;
extern BulletStateDefaultTypeInternal _BulletState_default_instance_;
class EnemyState;
struct EnemyStateDefaultTypeInternal;
extern EnemyStateDefaultTypeInternal _EnemyState_default_instance_;
class GameSnapshot;
struct GameSnapshotDefaultTypeInternal;
extern GameSnapshotDefaultTypeInternal _GameSnapshot_default_instance_;
class LoginResponse;
struct LoginResponseDefaultTypeInternal;
extern LoginResponseDefaultTypeInternal _LoginResponse_default_instance_;
class PlayerInput;
struct PlayerInputDefaultTypeInternal;
extern PlayerInputDefaultTypeInternal _PlayerInput_default_instance_;
class PlayerState;
struct PlayerStateDefaultTypeInternal;
extern PlayerStateDefaultTypeInternal _PlayerState_default_instance_;
}  // namespace game
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace game {
enum PlayerInput_InputType : int {
  PlayerInput_InputType_NONE = 0,
  PlayerInput_InputType_UP = 1,
  PlayerInput_InputType_DOWN = 2,
  PlayerInput_InputType_LEFT = 3,
  PlayerInput_InputType_RIGHT = 4,
  PlayerInput_InputType_FIRE = 5,
  PlayerInput_InputType_PlayerInput_InputType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  PlayerInput_InputType_PlayerInput_InputType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool PlayerInput_InputType_IsValid(int value);
extern const uint32_t PlayerInput_InputType_internal_data_[];
constexpr PlayerInput_InputType PlayerInput_InputType_InputType_MIN = static_cast<PlayerInput_InputType>(0);
constexpr PlayerInput_InputType PlayerInput_InputType_InputType_MAX = static_cast<PlayerInput_InputType>(5);
constexpr int PlayerInput_InputType_InputType_ARRAYSIZE = 5 + 1;
const ::google::protobuf::EnumDescriptor*
PlayerInput_InputType_descriptor();
template <typename T>
const std::string& PlayerInput_InputType_Name(T value) {
  static_assert(std::is_same<T, PlayerInput_InputType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to InputType_Name().");
  return PlayerInput_InputType_Name(static_cast<PlayerInput_InputType>(value));
}
template <>
inline const std::string& PlayerInput_InputType_Name(PlayerInput_InputType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<PlayerInput_InputType_descriptor,
                                                 0, 5>(
      static_cast<int>(value));
}
inline bool PlayerInput_InputType_Parse(absl::string_view name, PlayerInput_InputType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<PlayerInput_InputType>(
      PlayerInput_InputType_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class PlayerState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game.PlayerState) */ {
 public:
  inline PlayerState() : PlayerState(nullptr) {}
  ~PlayerState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlayerState* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlayerState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlayerState(
      ::google::protobuf::internal::ConstantInitialized);

  inline PlayerState(const PlayerState& from) : PlayerState(nullptr, from) {}
  inline PlayerState(PlayerState&& from) noexcept
      : PlayerState(nullptr, std::move(from)) {}
  inline PlayerState& operator=(const PlayerState& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerState& operator=(PlayerState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerState& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerState* internal_default_instance() {
    return reinterpret_cast<const PlayerState*>(
        &_PlayerState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(PlayerState& a, PlayerState& b) { a.Swap(&b); }
  inline void Swap(PlayerState* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerState* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlayerState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlayerState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlayerState& from) { PlayerState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlayerState* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game.PlayerState"; }

 protected:
  explicit PlayerState(::google::protobuf::Arena* arena);
  PlayerState(::google::protobuf::Arena* arena, const PlayerState& from);
  PlayerState(::google::protobuf::Arena* arena, PlayerState&& from) noexcept
      : PlayerState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kAngleFieldNumber = 4,
  };
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // float x = 2;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 3;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // float angle = 4;
  void clear_angle() ;
  float angle() const;
  void set_angle(float value);

  private:
  float _internal_angle() const;
  void _internal_set_angle(float value);

  public:
  // @@protoc_insertion_point(class_scope:game.PlayerState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PlayerState& from_msg);
    ::int32_t id_;
    float x_;
    float y_;
    float angle_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class PlayerInput final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game.PlayerInput) */ {
 public:
  inline PlayerInput() : PlayerInput(nullptr) {}
  ~PlayerInput() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(PlayerInput* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(PlayerInput));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR PlayerInput(
      ::google::protobuf::internal::ConstantInitialized);

  inline PlayerInput(const PlayerInput& from) : PlayerInput(nullptr, from) {}
  inline PlayerInput(PlayerInput&& from) noexcept
      : PlayerInput(nullptr, std::move(from)) {}
  inline PlayerInput& operator=(const PlayerInput& from) {
    CopyFrom(from);
    return *this;
  }
  inline PlayerInput& operator=(PlayerInput&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const PlayerInput& default_instance() {
    return *internal_default_instance();
  }
  static inline const PlayerInput* internal_default_instance() {
    return reinterpret_cast<const PlayerInput*>(
        &_PlayerInput_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(PlayerInput& a, PlayerInput& b) { a.Swap(&b); }
  inline void Swap(PlayerInput* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PlayerInput* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  PlayerInput* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<PlayerInput>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const PlayerInput& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const PlayerInput& from) { PlayerInput::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(PlayerInput* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game.PlayerInput"; }

 protected:
  explicit PlayerInput(::google::protobuf::Arena* arena);
  PlayerInput(::google::protobuf::Arena* arena, const PlayerInput& from);
  PlayerInput(::google::protobuf::Arena* arena, PlayerInput&& from) noexcept
      : PlayerInput(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using InputType = PlayerInput_InputType;
  static constexpr InputType NONE = PlayerInput_InputType_NONE;
  static constexpr InputType UP = PlayerInput_InputType_UP;
  static constexpr InputType DOWN = PlayerInput_InputType_DOWN;
  static constexpr InputType LEFT = PlayerInput_InputType_LEFT;
  static constexpr InputType RIGHT = PlayerInput_InputType_RIGHT;
  static constexpr InputType FIRE = PlayerInput_InputType_FIRE;
  static inline bool InputType_IsValid(int value) {
    return PlayerInput_InputType_IsValid(value);
  }
  static constexpr InputType InputType_MIN = PlayerInput_InputType_InputType_MIN;
  static constexpr InputType InputType_MAX = PlayerInput_InputType_InputType_MAX;
  static constexpr int InputType_ARRAYSIZE = PlayerInput_InputType_InputType_ARRAYSIZE;
  static inline const ::google::protobuf::EnumDescriptor* InputType_descriptor() {
    return PlayerInput_InputType_descriptor();
  }
  template <typename T>
  static inline const std::string& InputType_Name(T value) {
    return PlayerInput_InputType_Name(value);
  }
  static inline bool InputType_Parse(absl::string_view name, InputType* value) {
    return PlayerInput_InputType_Parse(name, value);
  }

  // accessors -------------------------------------------------------
  enum : int {
    kPlayerIdFieldNumber = 1,
    kInputFieldNumber = 2,
  };
  // int32 player_id = 1;
  void clear_player_id() ;
  ::int32_t player_id() const;
  void set_player_id(::int32_t value);

  private:
  ::int32_t _internal_player_id() const;
  void _internal_set_player_id(::int32_t value);

  public:
  // .game.PlayerInput.InputType input = 2;
  void clear_input() ;
  ::game::PlayerInput_InputType input() const;
  void set_input(::game::PlayerInput_InputType value);

  private:
  ::game::PlayerInput_InputType _internal_input() const;
  void _internal_set_input(::game::PlayerInput_InputType value);

  public:
  // @@protoc_insertion_point(class_scope:game.PlayerInput)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const PlayerInput& from_msg);
    ::int32_t player_id_;
    int input_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class LoginResponse final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game.LoginResponse) */ {
 public:
  inline LoginResponse() : LoginResponse(nullptr) {}
  ~LoginResponse() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(LoginResponse* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(LoginResponse));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR LoginResponse(
      ::google::protobuf::internal::ConstantInitialized);

  inline LoginResponse(const LoginResponse& from) : LoginResponse(nullptr, from) {}
  inline LoginResponse(LoginResponse&& from) noexcept
      : LoginResponse(nullptr, std::move(from)) {}
  inline LoginResponse& operator=(const LoginResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline LoginResponse& operator=(LoginResponse&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const LoginResponse& default_instance() {
    return *internal_default_instance();
  }
  static inline const LoginResponse* internal_default_instance() {
    return reinterpret_cast<const LoginResponse*>(
        &_LoginResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(LoginResponse& a, LoginResponse& b) { a.Swap(&b); }
  inline void Swap(LoginResponse* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(LoginResponse* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  LoginResponse* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<LoginResponse>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const LoginResponse& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const LoginResponse& from) { LoginResponse::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(LoginResponse* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game.LoginResponse"; }

 protected:
  explicit LoginResponse(::google::protobuf::Arena* arena);
  LoginResponse(::google::protobuf::Arena* arena, const LoginResponse& from);
  LoginResponse(::google::protobuf::Arena* arena, LoginResponse&& from) noexcept
      : LoginResponse(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kYourIdFieldNumber = 1,
    kInitXFieldNumber = 2,
    kInitYFieldNumber = 3,
  };
  // int32 your_id = 1;
  void clear_your_id() ;
  ::int32_t your_id() const;
  void set_your_id(::int32_t value);

  private:
  ::int32_t _internal_your_id() const;
  void _internal_set_your_id(::int32_t value);

  public:
  // float init_x = 2;
  void clear_init_x() ;
  float init_x() const;
  void set_init_x(float value);

  private:
  float _internal_init_x() const;
  void _internal_set_init_x(float value);

  public:
  // float init_y = 3;
  void clear_init_y() ;
  float init_y() const;
  void set_init_y(float value);

  private:
  float _internal_init_y() const;
  void _internal_set_init_y(float value);

  public:
  // @@protoc_insertion_point(class_scope:game.LoginResponse)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const LoginResponse& from_msg);
    ::int32_t your_id_;
    float init_x_;
    float init_y_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class EnemyState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game.EnemyState) */ {
 public:
  inline EnemyState() : EnemyState(nullptr) {}
  ~EnemyState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(EnemyState* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(EnemyState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR EnemyState(
      ::google::protobuf::internal::ConstantInitialized);

  inline EnemyState(const EnemyState& from) : EnemyState(nullptr, from) {}
  inline EnemyState(EnemyState&& from) noexcept
      : EnemyState(nullptr, std::move(from)) {}
  inline EnemyState& operator=(const EnemyState& from) {
    CopyFrom(from);
    return *this;
  }
  inline EnemyState& operator=(EnemyState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const EnemyState& default_instance() {
    return *internal_default_instance();
  }
  static inline const EnemyState* internal_default_instance() {
    return reinterpret_cast<const EnemyState*>(
        &_EnemyState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(EnemyState& a, EnemyState& b) { a.Swap(&b); }
  inline void Swap(EnemyState* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(EnemyState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  EnemyState* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<EnemyState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const EnemyState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const EnemyState& from) { EnemyState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(EnemyState* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game.EnemyState"; }

 protected:
  explicit EnemyState(::google::protobuf::Arena* arena);
  EnemyState(::google::protobuf::Arena* arena, const EnemyState& from);
  EnemyState(::google::protobuf::Arena* arena, EnemyState&& from) noexcept
      : EnemyState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kTypeFieldNumber = 4,
    kHealthFieldNumber = 5,
  };
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // float x = 2;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 3;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // int32 type = 4;
  void clear_type() ;
  ::int32_t type() const;
  void set_type(::int32_t value);

  private:
  ::int32_t _internal_type() const;
  void _internal_set_type(::int32_t value);

  public:
  // int32 health = 5;
  void clear_health() ;
  ::int32_t health() const;
  void set_health(::int32_t value);

  private:
  ::int32_t _internal_health() const;
  void _internal_set_health(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:game.EnemyState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 5, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const EnemyState& from_msg);
    ::int32_t id_;
    float x_;
    float y_;
    ::int32_t type_;
    ::int32_t health_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class BulletState final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game.BulletState) */ {
 public:
  inline BulletState() : BulletState(nullptr) {}
  ~BulletState() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(BulletState* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(BulletState));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR BulletState(
      ::google::protobuf::internal::ConstantInitialized);

  inline BulletState(const BulletState& from) : BulletState(nullptr, from) {}
  inline BulletState(BulletState&& from) noexcept
      : BulletState(nullptr, std::move(from)) {}
  inline BulletState& operator=(const BulletState& from) {
    CopyFrom(from);
    return *this;
  }
  inline BulletState& operator=(BulletState&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const BulletState& default_instance() {
    return *internal_default_instance();
  }
  static inline const BulletState* internal_default_instance() {
    return reinterpret_cast<const BulletState*>(
        &_BulletState_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(BulletState& a, BulletState& b) { a.Swap(&b); }
  inline void Swap(BulletState* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(BulletState* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  BulletState* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<BulletState>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const BulletState& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const BulletState& from) { BulletState::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(BulletState* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game.BulletState"; }

 protected:
  explicit BulletState(::google::protobuf::Arena* arena);
  BulletState(::google::protobuf::Arena* arena, const BulletState& from);
  BulletState(::google::protobuf::Arena* arena, BulletState&& from) noexcept
      : BulletState(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kIdFieldNumber = 1,
    kXFieldNumber = 2,
    kYFieldNumber = 3,
    kTypeFieldNumber = 4,
  };
  // int32 id = 1;
  void clear_id() ;
  ::int32_t id() const;
  void set_id(::int32_t value);

  private:
  ::int32_t _internal_id() const;
  void _internal_set_id(::int32_t value);

  public:
  // float x = 2;
  void clear_x() ;
  float x() const;
  void set_x(float value);

  private:
  float _internal_x() const;
  void _internal_set_x(float value);

  public:
  // float y = 3;
  void clear_y() ;
  float y() const;
  void set_y(float value);

  private:
  float _internal_y() const;
  void _internal_set_y(float value);

  public:
  // int32 type = 4;
  void clear_type() ;
  ::int32_t type() const;
  void set_type(::int32_t value);

  private:
  ::int32_t _internal_type() const;
  void _internal_set_type(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:game.BulletState)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 4, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const BulletState& from_msg);
    ::int32_t id_;
    float x_;
    float y_;
    ::int32_t type_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};
// -------------------------------------------------------------------

class GameSnapshot final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:game.GameSnapshot) */ {
 public:
  inline GameSnapshot() : GameSnapshot(nullptr) {}
  ~GameSnapshot() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(GameSnapshot* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(GameSnapshot));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR GameSnapshot(
      ::google::protobuf::internal::ConstantInitialized);

  inline GameSnapshot(const GameSnapshot& from) : GameSnapshot(nullptr, from) {}
  inline GameSnapshot(GameSnapshot&& from) noexcept
      : GameSnapshot(nullptr, std::move(from)) {}
  inline GameSnapshot& operator=(const GameSnapshot& from) {
    CopyFrom(from);
    return *this;
  }
  inline GameSnapshot& operator=(GameSnapshot&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const GameSnapshot& default_instance() {
    return *internal_default_instance();
  }
  static inline const GameSnapshot* internal_default_instance() {
    return reinterpret_cast<const GameSnapshot*>(
        &_GameSnapshot_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 5;
  friend void swap(GameSnapshot& a, GameSnapshot& b) { a.Swap(&b); }
  inline void Swap(GameSnapshot* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(GameSnapshot* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  GameSnapshot* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<GameSnapshot>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const GameSnapshot& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const GameSnapshot& from) { GameSnapshot::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(GameSnapshot* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "game.GameSnapshot"; }

 protected:
  explicit GameSnapshot(::google::protobuf::Arena* arena);
  GameSnapshot(::google::protobuf::Arena* arena, const GameSnapshot& from);
  GameSnapshot(::google::protobuf::Arena* arena, GameSnapshot&& from) noexcept
      : GameSnapshot(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kPlayersFieldNumber = 1,
    kBulletsFieldNumber = 2,
    kEnemiesFieldNumber = 3,
  };
  // repeated .game.PlayerState players = 1;
  int players_size() const;
  private:
  int _internal_players_size() const;

  public:
  void clear_players() ;
  ::game::PlayerState* mutable_players(int index);
  ::google::protobuf::RepeatedPtrField<::game::PlayerState>* mutable_players();

  private:
  const ::google::protobuf::RepeatedPtrField<::game::PlayerState>& _internal_players() const;
  ::google::protobuf::RepeatedPtrField<::game::PlayerState>* _internal_mutable_players();
  public:
  const ::game::PlayerState& players(int index) const;
  ::game::PlayerState* add_players();
  const ::google::protobuf::RepeatedPtrField<::game::PlayerState>& players() const;
  // repeated .game.BulletState bullets = 2;
  int bullets_size() const;
  private:
  int _internal_bullets_size() const;

  public:
  void clear_bullets() ;
  ::game::BulletState* mutable_bullets(int index);
  ::google::protobuf::RepeatedPtrField<::game::BulletState>* mutable_bullets();

  private:
  const ::google::protobuf::RepeatedPtrField<::game::BulletState>& _internal_bullets() const;
  ::google::protobuf::RepeatedPtrField<::game::BulletState>* _internal_mutable_bullets();
  public:
  const ::game::BulletState& bullets(int index) const;
  ::game::BulletState* add_bullets();
  const ::google::protobuf::RepeatedPtrField<::game::BulletState>& bullets() const;
  // repeated .game.EnemyState enemies = 3;
  int enemies_size() const;
  private:
  int _internal_enemies_size() const;

  public:
  void clear_enemies() ;
  ::game::EnemyState* mutable_enemies(int index);
  ::google::protobuf::RepeatedPtrField<::game::EnemyState>* mutable_enemies();

  private:
  const ::google::protobuf::RepeatedPtrField<::game::EnemyState>& _internal_enemies() const;
  ::google::protobuf::RepeatedPtrField<::game::EnemyState>* _internal_mutable_enemies();
  public:
  const ::game::EnemyState& enemies(int index) const;
  ::game::EnemyState* add_enemies();
  const ::google::protobuf::RepeatedPtrField<::game::EnemyState>& enemies() const;
  // @@protoc_insertion_point(class_scope:game.GameSnapshot)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 3,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const GameSnapshot& from_msg);
    ::google::protobuf::RepeatedPtrField< ::game::PlayerState > players_;
    ::google::protobuf::RepeatedPtrField< ::game::BulletState > bullets_;
    ::google::protobuf::RepeatedPtrField< ::game::EnemyState > enemies_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_game_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// LoginResponse

// int32 your_id = 1;
inline void LoginResponse::clear_your_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.your_id_ = 0;
}
inline ::int32_t LoginResponse::your_id() const {
  // @@protoc_insertion_point(field_get:game.LoginResponse.your_id)
  return _internal_your_id();
}
inline void LoginResponse::set_your_id(::int32_t value) {
  _internal_set_your_id(value);
  // @@protoc_insertion_point(field_set:game.LoginResponse.your_id)
}
inline ::int32_t LoginResponse::_internal_your_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.your_id_;
}
inline void LoginResponse::_internal_set_your_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.your_id_ = value;
}

// float init_x = 2;
inline void LoginResponse::clear_init_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.init_x_ = 0;
}
inline float LoginResponse::init_x() const {
  // @@protoc_insertion_point(field_get:game.LoginResponse.init_x)
  return _internal_init_x();
}
inline void LoginResponse::set_init_x(float value) {
  _internal_set_init_x(value);
  // @@protoc_insertion_point(field_set:game.LoginResponse.init_x)
}
inline float LoginResponse::_internal_init_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.init_x_;
}
inline void LoginResponse::_internal_set_init_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.init_x_ = value;
}

// float init_y = 3;
inline void LoginResponse::clear_init_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.init_y_ = 0;
}
inline float LoginResponse::init_y() const {
  // @@protoc_insertion_point(field_get:game.LoginResponse.init_y)
  return _internal_init_y();
}
inline void LoginResponse::set_init_y(float value) {
  _internal_set_init_y(value);
  // @@protoc_insertion_point(field_set:game.LoginResponse.init_y)
}
inline float LoginResponse::_internal_init_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.init_y_;
}
inline void LoginResponse::_internal_set_init_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.init_y_ = value;
}

// -------------------------------------------------------------------

// PlayerInput

// int32 player_id = 1;
inline void PlayerInput::clear_player_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_id_ = 0;
}
inline ::int32_t PlayerInput::player_id() const {
  // @@protoc_insertion_point(field_get:game.PlayerInput.player_id)
  return _internal_player_id();
}
inline void PlayerInput::set_player_id(::int32_t value) {
  _internal_set_player_id(value);
  // @@protoc_insertion_point(field_set:game.PlayerInput.player_id)
}
inline ::int32_t PlayerInput::_internal_player_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.player_id_;
}
inline void PlayerInput::_internal_set_player_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.player_id_ = value;
}

// .game.PlayerInput.InputType input = 2;
inline void PlayerInput::clear_input() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.input_ = 0;
}
inline ::game::PlayerInput_InputType PlayerInput::input() const {
  // @@protoc_insertion_point(field_get:game.PlayerInput.input)
  return _internal_input();
}
inline void PlayerInput::set_input(::game::PlayerInput_InputType value) {
  _internal_set_input(value);
  // @@protoc_insertion_point(field_set:game.PlayerInput.input)
}
inline ::game::PlayerInput_InputType PlayerInput::_internal_input() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::game::PlayerInput_InputType>(_impl_.input_);
}
inline void PlayerInput::_internal_set_input(::game::PlayerInput_InputType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.input_ = value;
}

// -------------------------------------------------------------------

// PlayerState

// int32 id = 1;
inline void PlayerState::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
}
inline ::int32_t PlayerState::id() const {
  // @@protoc_insertion_point(field_get:game.PlayerState.id)
  return _internal_id();
}
inline void PlayerState::set_id(::int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:game.PlayerState.id)
}
inline ::int32_t PlayerState::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void PlayerState::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// float x = 2;
inline void PlayerState::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline float PlayerState::x() const {
  // @@protoc_insertion_point(field_get:game.PlayerState.x)
  return _internal_x();
}
inline void PlayerState::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:game.PlayerState.x)
}
inline float PlayerState::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void PlayerState::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 3;
inline void PlayerState::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline float PlayerState::y() const {
  // @@protoc_insertion_point(field_get:game.PlayerState.y)
  return _internal_y();
}
inline void PlayerState::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:game.PlayerState.y)
}
inline float PlayerState::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void PlayerState::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// float angle = 4;
inline void PlayerState::clear_angle() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angle_ = 0;
}
inline float PlayerState::angle() const {
  // @@protoc_insertion_point(field_get:game.PlayerState.angle)
  return _internal_angle();
}
inline void PlayerState::set_angle(float value) {
  _internal_set_angle(value);
  // @@protoc_insertion_point(field_set:game.PlayerState.angle)
}
inline float PlayerState::_internal_angle() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.angle_;
}
inline void PlayerState::_internal_set_angle(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.angle_ = value;
}

// -------------------------------------------------------------------

// BulletState

// int32 id = 1;
inline void BulletState::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
}
inline ::int32_t BulletState::id() const {
  // @@protoc_insertion_point(field_get:game.BulletState.id)
  return _internal_id();
}
inline void BulletState::set_id(::int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:game.BulletState.id)
}
inline ::int32_t BulletState::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void BulletState::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// float x = 2;
inline void BulletState::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline float BulletState::x() const {
  // @@protoc_insertion_point(field_get:game.BulletState.x)
  return _internal_x();
}
inline void BulletState::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:game.BulletState.x)
}
inline float BulletState::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void BulletState::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 3;
inline void BulletState::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline float BulletState::y() const {
  // @@protoc_insertion_point(field_get:game.BulletState.y)
  return _internal_y();
}
inline void BulletState::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:game.BulletState.y)
}
inline float BulletState::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void BulletState::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// int32 type = 4;
inline void BulletState::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::int32_t BulletState::type() const {
  // @@protoc_insertion_point(field_get:game.BulletState.type)
  return _internal_type();
}
inline void BulletState::set_type(::int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:game.BulletState.type)
}
inline ::int32_t BulletState::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_;
}
inline void BulletState::_internal_set_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// -------------------------------------------------------------------

// EnemyState

// int32 id = 1;
inline void EnemyState::clear_id() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = 0;
}
inline ::int32_t EnemyState::id() const {
  // @@protoc_insertion_point(field_get:game.EnemyState.id)
  return _internal_id();
}
inline void EnemyState::set_id(::int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:game.EnemyState.id)
}
inline ::int32_t EnemyState::_internal_id() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.id_;
}
inline void EnemyState::_internal_set_id(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.id_ = value;
}

// float x = 2;
inline void EnemyState::clear_x() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = 0;
}
inline float EnemyState::x() const {
  // @@protoc_insertion_point(field_get:game.EnemyState.x)
  return _internal_x();
}
inline void EnemyState::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:game.EnemyState.x)
}
inline float EnemyState::_internal_x() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.x_;
}
inline void EnemyState::_internal_set_x(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.x_ = value;
}

// float y = 3;
inline void EnemyState::clear_y() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = 0;
}
inline float EnemyState::y() const {
  // @@protoc_insertion_point(field_get:game.EnemyState.y)
  return _internal_y();
}
inline void EnemyState::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:game.EnemyState.y)
}
inline float EnemyState::_internal_y() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.y_;
}
inline void EnemyState::_internal_set_y(float value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.y_ = value;
}

// int32 type = 4;
inline void EnemyState::clear_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = 0;
}
inline ::int32_t EnemyState::type() const {
  // @@protoc_insertion_point(field_get:game.EnemyState.type)
  return _internal_type();
}
inline void EnemyState::set_type(::int32_t value) {
  _internal_set_type(value);
  // @@protoc_insertion_point(field_set:game.EnemyState.type)
}
inline ::int32_t EnemyState::_internal_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.type_;
}
inline void EnemyState::_internal_set_type(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.type_ = value;
}

// int32 health = 5;
inline void EnemyState::clear_health() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.health_ = 0;
}
inline ::int32_t EnemyState::health() const {
  // @@protoc_insertion_point(field_get:game.EnemyState.health)
  return _internal_health();
}
inline void EnemyState::set_health(::int32_t value) {
  _internal_set_health(value);
  // @@protoc_insertion_point(field_set:game.EnemyState.health)
}
inline ::int32_t EnemyState::_internal_health() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.health_;
}
inline void EnemyState::_internal_set_health(::int32_t value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.health_ = value;
}

// -------------------------------------------------------------------

// GameSnapshot

// repeated .game.PlayerState players = 1;
inline int GameSnapshot::_internal_players_size() const {
  return _internal_players().size();
}
inline int GameSnapshot::players_size() const {
  return _internal_players_size();
}
inline void GameSnapshot::clear_players() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.players_.Clear();
}
inline ::game::PlayerState* GameSnapshot::mutable_players(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:game.GameSnapshot.players)
  return _internal_mutable_players()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::game::PlayerState>* GameSnapshot::mutable_players()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:game.GameSnapshot.players)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_players();
}
inline const ::game::PlayerState& GameSnapshot::players(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game.GameSnapshot.players)
  return _internal_players().Get(index);
}
inline ::game::PlayerState* GameSnapshot::add_players() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::game::PlayerState* _add = _internal_mutable_players()->Add();
  // @@protoc_insertion_point(field_add:game.GameSnapshot.players)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::game::PlayerState>& GameSnapshot::players() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:game.GameSnapshot.players)
  return _internal_players();
}
inline const ::google::protobuf::RepeatedPtrField<::game::PlayerState>&
GameSnapshot::_internal_players() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.players_;
}
inline ::google::protobuf::RepeatedPtrField<::game::PlayerState>*
GameSnapshot::_internal_mutable_players() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.players_;
}

// repeated .game.BulletState bullets = 2;
inline int GameSnapshot::_internal_bullets_size() const {
  return _internal_bullets().size();
}
inline int GameSnapshot::bullets_size() const {
  return _internal_bullets_size();
}
inline void GameSnapshot::clear_bullets() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bullets_.Clear();
}
inline ::game::BulletState* GameSnapshot::mutable_bullets(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:game.GameSnapshot.bullets)
  return _internal_mutable_bullets()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::game::BulletState>* GameSnapshot::mutable_bullets()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:game.GameSnapshot.bullets)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_bullets();
}
inline const ::game::BulletState& GameSnapshot::bullets(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game.GameSnapshot.bullets)
  return _internal_bullets().Get(index);
}
inline ::game::BulletState* GameSnapshot::add_bullets() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::game::BulletState* _add = _internal_mutable_bullets()->Add();
  // @@protoc_insertion_point(field_add:game.GameSnapshot.bullets)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::game::BulletState>& GameSnapshot::bullets() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:game.GameSnapshot.bullets)
  return _internal_bullets();
}
inline const ::google::protobuf::RepeatedPtrField<::game::BulletState>&
GameSnapshot::_internal_bullets() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bullets_;
}
inline ::google::protobuf::RepeatedPtrField<::game::BulletState>*
GameSnapshot::_internal_mutable_bullets() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.bullets_;
}

// repeated .game.EnemyState enemies = 3;
inline int GameSnapshot::_internal_enemies_size() const {
  return _internal_enemies().size();
}
inline int GameSnapshot::enemies_size() const {
  return _internal_enemies_size();
}
inline void GameSnapshot::clear_enemies() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enemies_.Clear();
}
inline ::game::EnemyState* GameSnapshot::mutable_enemies(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:game.GameSnapshot.enemies)
  return _internal_mutable_enemies()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::game::EnemyState>* GameSnapshot::mutable_enemies()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:game.GameSnapshot.enemies)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_enemies();
}
inline const ::game::EnemyState& GameSnapshot::enemies(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:game.GameSnapshot.enemies)
  return _internal_enemies().Get(index);
}
inline ::game::EnemyState* GameSnapshot::add_enemies() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::game::EnemyState* _add = _internal_mutable_enemies()->Add();
  // @@protoc_insertion_point(field_add:game.GameSnapshot.enemies)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::game::EnemyState>& GameSnapshot::enemies() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:game.GameSnapshot.enemies)
  return _internal_enemies();
}
inline const ::google::protobuf::RepeatedPtrField<::game::EnemyState>&
GameSnapshot::_internal_enemies() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enemies_;
}
inline ::google::protobuf::RepeatedPtrField<::game::EnemyState>*
GameSnapshot::_internal_mutable_enemies() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.enemies_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace game


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::game::PlayerInput_InputType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::game::PlayerInput_InputType>() {
  return ::game::PlayerInput_InputType_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // game_2eproto_2epb_2eh
